# Generated by Django 3.2 on 2023-07-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
